title: Exoplanet imaging data challenge
description:
show_downloads: false
git_branch: master
logo_url:
google_analytics: UA-84473187-3
theme: jekyll-theme-cayman
wiki_folder: wiki
use_github_wiki: false
use_prose_io: true
google_cse_token: 
custom_head: false
custom_sidebar: false
custom_footer: false

author :
  name : Carlos Alberto Gomez Gonzalez
  email : carlosgg33@gmail.com
  github : carlgogo

gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
