title: Exoplanet Imaging Challenge
description: Data challenge for exoplanets direct detection and characterization with high-contrast imaging
show_downloads: false
git_branch: master
logo_url: assets/images/challenge_logo_LR.png
google_analytics: UA-84473187-3
google_cse_token:
use_prose_io: true
custom_head: false
custom_sidebar: false
custom_footer: false

author :
  name : Carlos Alberto Gomez Gonzalez
  email : carlosgg33@gmail.com
  github : carlgogo

gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed

theme:
wiki_folder: wiki
use_github_wiki: false