title: Exoplanet imaging data challenge
description:
show_downloads: false
git_branch: master
logo_url:
google_analytics:
theme: fongandrew/hydeout
wiki_folder: wiki
use_github_wiki: false
use_prose_io: true
google_cse_token: 
custom_head: false
custom_sidebar: false
custom_footer: false

author :
  name : Carlos Alberto Gomez Gonzalez
  email : carlosgg33@gmail.com
  github : carlgogo

jekyll_analytics:
  GoogleAnalytics:             # Add, if you want to track with Google Analytics
    id: UA-84473187-3          # Required - replace with your tracking id
    anonymizeIp: false         # Optional - Default: false - set to true for anonymized tracking

gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-analytics
